name: Apply summary
on:
  workflow_dispatch:
    inputs:
      workflow_apply_url:
        description: URL to the workflow run for the terraform apply execution
        type: string
        required: true
      status:
        description: Request status
        type: string
        required: true

permissions:
  contents: read

jobs:
  apply_callback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO: add a step to display the apply summary within the workflow summary
      - name: Update workflow summary with apply execution details
        if: ${{ inputs.status == 'APPLY_SUCCESS' || inputs.status == 'APPLY_FAILURE' }}
        env:
          WORKFLOW_APPLY_URL: ${{ inputs.workflow_apply_url }}
          STATUS: ${{ inputs.status }}
        run: |
          echo "## Terraform Apply Execution Details" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Status: $STATUS" >> $GITHUB_STEP_SUMMARY
          echo "Workflow Apply URL: $WORKFLOW_APPLY_URL" >> $GITHUB_STEP_SUMMARY
