name: Create request
on:
  workflow_dispatch:
    inputs:
      # TODO: replace tfvars_content by inputs used to generate the tfvars content
      tfvars_content:
        description: tfvars content (input provided for testing purpose, in real case, it is generated during the workflow execution)
        type: string
        required: true
      product_id:
        description: product id (input provided for testing purpose, in real case, product id is generated during the workflow execution)
        type: string
        required: true
      product_type:
        description: Product type (e.g vm_creation, gke_creation)
        type: string
        required: true
      environment:
        description: Github environment in the 'Provisioning' repository
        type: string
        required: true
      # TODO: might be linked to the product type provided
      repository:
        description: Repository containing the terraform configuration used
        type: string
        required: true
      repository_version:
        description: Version of the repository containing the terraform configuration (tag, sha...)
        type: string
        required: true

permissions:
  contents: read
  issues: write

jobs:
  # TODO: generation of tfvars content and product ID based on inputs should be executed before the request creation

  # TODO: generate installation access tokens instead of using PATs
  initialize_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      # - name: Create request
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # TODO: use labels or something to attach a state to the issue (labels must exist at the repo level before linking those to issues)
      #     ISSUE_TITLE="${{ inputs.product_type }}: provisioning of ${{ inputs.product_id }}"
      #     ISSUE_BODY="${{ inputs.tfvars_content }}"
      #     gh issue create --label 'infra: to be started' --title "$ISSUE_TITLE" --body "$ISSUE_BODY"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install PyGithub

      # TODO: check if tfvars content should be added too
      - name: Create request issue
        id: create
        env:
          TITLE: "[${{ inputs.product_type }}]: provisioning of ${{ inputs.product_id }}"
          INITIAL_DATA_JSON: >-
            {
              "product_id":"${{ inputs.product_id }}",
              "product_type":"${{ inputs.product_type }}",
              "environment": "${{ inputs.environment }}",
              "repository": "${{ inputs.repository }}",
              "repository_version": "${{ inputs.repository_version }}",
              "requested_by": "${{ github.actor }}"
            }
          REQUEST_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # EXTRA_LABELS_JSON: '["product:${{ inputs.product }}"]'
        run: python3 scripts/transition_guard.py create

      
      - name: Call plan execution (workflow_dispatch)
        run: |
          # TODO: format the generated tfvars by escaping double quotes and line returns
          # TFVARS_FORMATED=$(echo "${{ inputs.tfvars_content }}" | sed 's/"/\\"/g' | awk 'NR>1{printf "\\n"} {printf "%s", $0}')

          TFVARS_FORMATED="${{ inputs.tfvars_content }}"
          cat <<-EOF > request_body.json
          {
            "ref":"main",
            "inputs":{
              "product_id":"${{ inputs.product_id }}",
              "product_type":"${{ inputs.product_type }}",
              "tfvars_content": "$TFVARS_FORMATED",
              "environment": "${{ inputs.environment }}",
              "repository": "${{ inputs.repository }}",
              "repository_version": "${{ inputs.repository_version }}"
            }
          }
          EOF

          echo 'request_body.json content:'
          cat request_body.json

          # TODO: use installation access token instead of PAT (must have Action (write) permission on called repo)
          # TODO: handle timeouts and non 200 responses: make job fails
          # TODO: get repository based on product type (with a map for example)???
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/repos/nmoun/workflows-cpa-build-on-gcp/actions/workflows/plan_dispatch.yaml/dispatches \
            -d @request_body.json


      # Notes: even if repository_dispatch seems simpler, token unfortunately requires "Contents" repository permissions (write)
      # - name: Call plan execution (repository_dispatch)
      #   run: |
      #     # TODO: format the generated tfvars by escaping double quotes and line returns
      #     # TFVARS_FORMATED=$(echo "${{ inputs.tfvars_content }}" | sed 's/"/\\"/g' | awk 'NR>1{printf "\\n"} {printf "%s", $0}')

      #     TFVARS_FORMATED="${{ inputs.tfvars_content }}"
      #     cat <<-EOF > request_body.json
      #     {
      #       "event_type": "launch_plan",
      #       "client_payload": {
      #         "product_id":"${{ inputs.product_id }}",
      #         "product_type":"${{ inputs.product_type }}",
      #         "tfvars_content": "$TFVARS_FORMATED",
      #         "environment": "${{ inputs.environment }}",
      #         "repository": "${{ inputs.repository }}",
      #         "repository_version": "${{ inputs.repository_version }}",
      #         "callback_repo": "${{ github.repository }}"
      #       }
      #     }
      #     EOF

      #     # TODO: use installation access token instead of PAT (must have Action (write) permission on called repo)
      #     # TODO: handle timeouts and non 200 responses: make job fails
      #     # TODO: get repository based on product type (with a map for example)???
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #       -H "X-GitHub-Api-Version: 2026-03-10" \
      #       https://api.github.com/repos/nmoun/workflows-cpa-build-on-gcp/dispatches \
      #       -d @request_body.json
